# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef7c42c0dd9701a771e24eaae0b0168d85356284bf9581008758317fe977fe9beb4061779295ce39064ae3c43b843964c0c3b652b94da9507e75d078c0c8a124

test:
  secret_key_base: e038cbac0d2751c6bf71e222228c77dc91caaa23965fa013cbe2d4d2718299cfec629f730fdbe4ec5a926bd79f7e8a258bef2899ca8e636878d43555e9a7f6d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
